version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/invoice
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_QUEUE=daily_sales_report
      - RECIPIENT_EMAIL=recipient@example.com
      - SENDGRID_API_KEY=your-sendgrid-api-key
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo-data:
